objects=\
compute_difference_image_hertzmann.o\
compute_difference_image_shiraishi_2.o\
compute_difference_image_shiraishi.o\
compute_equivalent_rectangle.o\
compute_image_moment.o\
compute_rectangle_points.o\
compute_reference_image.o\
free_texture_arr.o\
gaussian_blur_image_2.o\
gaussian_blur_image.o\
gaussian_blur_rgb_image.o\
get_grid_cell_median_color.o\
initialize_canvas_bumpity_image.o\
initialize_canvas_rgb_image.o\
load_texture_arr.o\
make_brush_stroke.o\
paint_brush_stroke.o\
paint_canvas.o\
paint_canvas_layer.o\
rotate_image.o\
rotate_image_cubic.o\
rotate_image_linear.o\
rotate_image_nearest_neighbor.o\
scale_image.o\
scale_image_cubic.o\
scale_image_linear.o\
scale_image_nearest_neighbor.o\
scale_rgb_image.o
